"""empty message

Revision ID: 225fdbf5a23d
Revises: 
Create Date: 2020-03-26 16:29:47.788119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225fdbf5a23d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test1',
    sa.Column('testid', sa.Integer(), nullable=False),
    sa.Column('creatorid', sa.String(), nullable=False),
    sa.Column('selected', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('testid')
    )
    
    op.create_table('quizquestions1',
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('option1', sa.String(), nullable=False),
    sa.Column('option2', sa.String(), nullable=False),
    sa.Column('option3', sa.String(), nullable=False),
    sa.Column('option4', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('creatorid', sa.String(), nullable=False),
    sa.Column('questionid', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('questionid')
    )
    op.create_table('quizuser1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('answered', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quizuser1')
    op.drop_table('quizquestions1')
    op.drop_table('test1')
    # ### end Alembic commands ###
